version: "3.4"
services:
  db:
    image:  mysql:latest
    ports:
       - "3300:3306"
    networks:
       - mynet
    environment:
      MYSQL_DATABASE: msdemo
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: secret
networks:
  mynet:
    driver: overlay