version: "3.4"
services:





  eurekaserver:
    image:   notix/eurekaserver:n1
    ports:
    - "8761:8761"
    networks:
    - mynet

  zuulserver:
    image: notix/zuulgateway:n1
    ports:
    - "8765:8765"
#    depends_on:
#    - eurekaserver
#    - rabbitmq
#    - zipkin
#    links:
#    - eurekaserver
#    - rabbitmq
#    - zipkin
    networks:
    - mynet

    environment:
      SERVER_PORT: 8765
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: 8761
      RABBIT_URI: "amqp://guest:guest@rabbitmq:5672"
      RABBIT_PORT: 5672
      ZIPKIN_URI: "http://localhost:9411"
      ENCRYPT_KEY:       "IMSYMMETRIC"

  converter:
    image: notix/currencyconverter:n1
    ports:
    - "8100:8100"
#    depends_on:
#    - eurekaserver
#    - rabbitmq
#    - zipkin
#    links:
#    - eurekaserver
#    - rabbitmq
#    - zipkin
    networks:
    - mynet

    environment:
      SERVER_PORT: 8100
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: 8761
      RABBIT_URI: "amqp://guest:guest@rabbitmq:5672"
      ZUULSERVER_PORT: 8765
      ZIPKIN_URI: "http://localhost:9411"
      ZIPKIN_PORT: 9411
      RABBIT_PORT: 5672
      ENCRYPT_KEY:       "IMSYMMETRIC"

  exchange:
    image: notix/exhangeservice:n1
    ports:
    - "8000:8000"
#    depends_on:
#    - eurekaserver
#    - rabbitmq
#    - zipkin
#    - db
#    links:
#    - eurekaserver
#    - rabbitmq
#    - zipkin
#    - db
    networks:
      - mynet


    environment:
      SERVER_PORT: 8000
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: 8761
      RABBIT_URI: "amqp://guest:guest@rabbitmq:5672"
      ZUULSERVER_PORT: 8765
      ZIPKIN_URI: "http://localhost:9411"
      ZIPKIN_PORT: 9411
      RABBIT_PORT: 5672
      MYSQL_PORT: 3306
      PROFILE: prod
      ENCRYPT_KEY:       "IMSYMMETRIC"
networks:
  mynet:
    driver: overlay







#    depends_on:
#    - rabbitmq
#    links:
#    - rabbitmq
#    environment:
#      RABBIT_URI: "amqp://guest:guest@rabbitmq:5672"

#    environment:
#      PROFILE: "default"
#      SERVER_PORT: "8765"