version: "3.4"
services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    #    hostname: rabbit
    expose:
    - 5672
    networks:
    - mynet
    #    deploy:
    #      replicas: 1

    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15672:15672"

    environment:
      RABBITMQ_USER : myuser
      RABBITMQ_PASS : mypass
networks:
  mynet:
    driver: overlay