version: "3.4"
services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    #    hostname: rabbit
    expose:
    - 5672
    networks:
    - mynet
#    deploy:
#      replicas: 1

    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15672:15672"
    #    links:
    #      - zipkin
    environment:
      #       RABBITMQ_NODENAME: rabbitmq
      RABBITMQ_USER : myuser
      RABBITMQ_PASS : mypass

  zipkin:
    image: openzipkin/zipkin
    ports:
    - 9411:9411
    depends_on:
    - rabbitmq
    links:
    - rabbitmq
    networks:
    - mynet

    environment:
      RABBIT_URI: "amqp://guest:guest@rabbitmq:5672"
#    deploy:
#      replicas: 1

networks:
  #  mydb:
  #    driver: overlay
  mynet:
    driver: overlay